# frozen_string_literal: true

ruby '2.7.5'

source 'https://rubygems.org'

github 'sinatra/sinatra' do
  gem 'sinatra'
  gem 'sinatra-contrib'
end

gem 'multi_json'

gem 'bcrypt'
gem 'rake'
gem 'rubocop'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'sqlite3'

group :test do
  gem 'rspec'
end
